### ISSUE TITLE
No need to recommend Extended Debugging by Erik Temple

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple-if.com#1]
The documentation recommends Extended Debugging by Erik Temple so that the debugging commands are available when testing a story.

It is not needed however, since it is possible to "release for testing" to preserve the debugging commands, at least on Windows and on macOS.

![image](https://user-images.githubusercontent.com/24978378/48091841-dce54a80-e1d8-11e8-908c-828425f9f978.png)

**Comment by juhana** [comment]
True! You don't mind if I use that screenshot in the documentation?

**Comment by Natrium729** [comment]
Sure! I have no objection to you using the screenshot.
