### ISSUE TITLE
Hyperlinks example "Mood Swings" contains code from "Click to Retry" example instead

### ISSUE THREAD

**Issue by pipik-roman** [vorple/vorple-if.com#3]
On webpage https://vorple-if.com/docs/extension-hyperlinks.html example "Mood Swings" contains code from different example instead:

![image](https://user-images.githubusercontent.com/810655/201822757-38cdcd24-c6dc-4089-a608-3e562a1f0c0b.png)

**Comment by juhana** [comment]
Thanks; the correct example is now in place.
